name: chainctl with pull token

on:
  workflow_dispatch: {}

jobs:
  chainctl-pull-token:
    name: chainctl pull token example
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Install chainctl
      run: |
          curl -o chainctl "https://dl.enforce.dev/chainctl/latest/chainctl_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/aarch64/arm64/')"
          sudo install -o root -g root -m 0755 chainctl /usr/bin/chainctl
          sudo ln -s /usr/bin/chainctl /usr/bin/docker-credential-cgr

    - name: Login to chainctl
      run: |
          chainctl auth login --identity=${{secrets.CGR_PULL_ID}} --identity-token=${{secrets.CGR_PULL_TOKEN}}
          chainctl auth configure-docker --identity=${{secrets.CGR_PULL_ID}} --identity-token=${{secrets.CGR_PULL_TOKEN}}

    - name: Execute chainctl command
      run: |
          chainctl image list
