# This is a basic workflow to help you get started with Actions

name: Chainguard Pull Example

on:
  # Triggers on push events for the "main" branch
  push:
    branches: [ "main" ]
  # Allow workflow to be triggered manually
  workflow_dispatch: {}
  # Allow workflow to be called by other workflows
  workflow_call: {}

permissions:
  contents: read
  # Required by Chainguard's OIDC federation.
  id-token: write

jobs:
  chainguard-pull:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install Chainctl
        uses: chainguard-dev/actions/setup-chainctl@main
        with:
          identity: ${{secrets.CHAINCTL_ID}}

      - name: Run Chainctl groups ls
        run: chainctl iam groups ls -o json

      # Pull Docker Images for each image in the array
      - name: Run Docker Pull
        run: |
          #!/usr/bin/env bash
          
          set -e
          
          registry="cgr.dev/scorwin.dev/"
          images=("curl:latest-dev" "kubectl:latest-dev" "node:latest-dev")
          
          # Iterate through the array using a for loop
          for image in "${images[@]}"; do
              echo "Current image: $image"
              docker pull "$registry$image"
          done
          
          docker image ls
