name: chainctl install

on:
  workflow_dispatch: {}

jobs:
  test-install:
    name: test install
    
    runs-on: ubuntu-latest
    
    steps:
    - name: Install chainctl
      run: |
          curl -o chainctl "https://dl.enforce.dev/chainctl/latest/chainctl_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/aarch64/arm64/')"
          sudo install -o root -g root -m 0755 chainctl /usr/bin/chainctl

    - name: Login to chainctl
      run: |
          chainctl auth login --identity=${{ secrets.CGR_IDENTITY }} --identity-token=${{ secrets.CGR_IDENTITY_TOKEN }}
          chainctl auth configure-docker --identity=${{ secrets.CGR_IDENTITY }} --identity-token=${{ secrets.CGR_IDENTITY_TOKEN }}
